const { FORM_SECTION_STATUS } = require("../../constants/index");
module.exports = (sequelize, DataTypes) => {
	const mainDashboard = sequelize.define(
		"TNRTP95_DASHBOARD_FORMS_MASTER",
		{
			TNRTP95_DASHBOARD_FORMS_MASTER_D: {
				type: DataTypes.INTEGER,
				primaryKey: true,
				autoIncrement: true,
			},
			formId: { type: DataTypes.INTEGER, field: "TNRTP95_FORMS_MASTER_D" },
			formTypeId: { type: DataTypes.INTEGER, field: "TNRTP95_FORMS_TYPE_D" },
			districtId: { type: DataTypes.INTEGER, field: "TNRTP95_US_DISTRICT_MASTER_D" },
			blockId: { type: DataTypes.INTEGER, field: "TNRTP95_US_BLOCK_MASTER_D" },
			panchayatId: { type: DataTypes.INTEGER, field: "TNRTP95_US_PANCHAYAT_MASTER_D" },
			totalDisburement: { type: DataTypes.INTEGER, field: "TNRTP95_TOTAL_DISBURSEMENT_AMOUNT_D" },
			applicationStatus: { type: DataTypes.INTEGER, field: "TNRTP95_IS_APPLICATION_STATUS_D" },

			totalMembers: { type: DataTypes.INTEGER, field: "TNRTP09_TOTAL_MEMBERS_D" },
			noOfActive: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_ACTIVE_D" },
			noOfInActive: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_INACTIVE_D" },
			activeInactiveTotal: { type: DataTypes.INTEGER, field: "TNRTP09_ACTIVE_INACTIVE_TOTAL_D" },
			noOfMale: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_MALE_D" },
			noOfFemale: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_FEMALE_D" },
			noOfTransGender: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_TRANSGENDER_D" },
			genderTotal: { type: DataTypes.INTEGER, field: "TNRTP09_GENDER_TOTAL_D" },
			noOfBC: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_BC_D" },
			noOfMBC: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_MBC_D" },
			noOfSC: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_SC_D" },
			noOfST: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_ST_D" },
			noOfCommunityOthers: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_COMMUNITY_OTHERS_D" },
			communityTotal: { type: DataTypes.INTEGER, field: "TNRTP09_COMMUNITY_TOTAL_D" },
			noOfMuslim: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_MUSLIMS_D" },
			noOfChristians: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_CHRISTIANS_D" },
			noOfMinorityOthers: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_MINORITY_OTHERS_D" },
			minorityTotal: { type: DataTypes.INTEGER, field: "TNRTP09_MINORITY_TOTAL_D" },
			noOfDiffAbled: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_DIFFERENTLY_ABLED_D" },
			noOfWidow: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_WIDOW_D" },
			noOfDesitute: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_DESTITUTE_WOMEN_D" },
			noOfDeserted: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_DESERTED_WOMEN_D" },
			noOfVulTransGender: {
				type: DataTypes.INTEGER,
				field: "TNRTP09_NO_OF_VULNERABLE_TRANSGENDER_D",
			},
			noOfEiderly: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_EIDERLY_D" },
			vulnerableTotal: { type: DataTypes.INTEGER, field: "TNRTP09_VULNERABLE_TOTAL_D" },
			noOfSHGMembers: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_SHG_MEMBERS_D" },
			noOfSHGTotal: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_SHG_HOUSE_HOLDS_D" },
			noOfNonSHGTotal: { type: DataTypes.INTEGER, field: "TNRTP09_NO_OF_NON_SHG_HOUSE_HOLDS_D" },
			shgTotal: { type: DataTypes.INTEGER, field: "TNRTP09_SHG_TOTAL_D" },
			status: {
				type: DataTypes.INTEGER,
				defaultValue: FORM_SECTION_STATUS.FILLED,
				field: "TNRTP81_STATUS_D",
			},
			TNRTP81_CREATED_AT: { type: DataTypes.DATE },
			TNRTP81_UPDATED_AT: { type: DataTypes.DATE },
			TNRTP81_CREATED_D: { type: DataTypes.INTEGER },
			TNRTP81_UPDATED_D: { type: DataTypes.INTEGER },
		},
		{
			freezeTableName: true,
			timestamps: false,
		}
	);
	mainDashboard.selectedFields = [
		"formId",
		"formTypeId",
		"totalDisburement",
		"applicationStatus",
		"totalMember",
		"totalGender",
		"totalCommunity",
		"totalSHG",
		"totalVulnerable",
		["TNRTP07_US_DISTRICT_MASTER_D", "district"],
		["TNRTP07_US_BLOCK_MASTER_D", "block"],
		["TNRTP07_US_PANCHAYAT_MASTER_D", "panchayat"],
	];
	return mainDashboard;
};
